---
- name: Create the namespace monitoring
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: grafana-operator  chart
  community.kubernetes.helm:
    atomic: true
    chart_repo_url: https://charts.bitnami.com/bitnami
    kubeconfig: "{{ kubeconfig_file }}"
    namespace: monitoring
    name: grafana-operator
    chart_ref: grafana-operator
    chart_version: 2.3.6
    wait_timeout: 10m
